@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJmaWZpQHRlc3QuY29tIiwiaWF0IjoxNzYzMTIwNDI4LCJleHAiOjE3NjMxMjQwMjh9.Od1hha1c9xK-RjlQpvjcrA96X4Wx-6yg7G83YSARlt8

### REGISTER (fonctionne)
POST http://localhost:1337/auth/local/register
Content-Type: application/json

{
  "nom": "tutu",
  "email": "fifi@test.com",
  "password": "test"
}

### LOGIN (fonctionne)
POST http://localhost:1337/auth/local
Content-Type: application/json

{
  "email": "fifi@test.com",
  "password": "test"
}

### Obtenir la liste de toutes les recettes (fonctionne)
GET http://localhost:1337/api/recettes
Content-Type: application/json


### Obtenir un ingredient
GET http://localhost:1337/api/ingredients/1
Content-Type: application/json


### Obtenir la liste des ingrédients (fonctionne) 
GET http://localhost:1337/api/ingredients
Content-Type: application/json

### Creer un ingredient
POST http://localhost:1337/api/ingredients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "nom_ingredients": "Patatis"
  }
}

### Obtenir une recette précise (documentId) (fonctionne)
GET http://localhost:1337/api/recettes/39ab41bd-dcb9-42b5-b16a-8e24c47041e5
Content-Type: application/json


### Créer une nouvelle recette  (fonctionne)
POST http://localhost:1337/api/recettes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "titre": "test data table",
    "temps_preparation": 30,
    "difficulte": 2,
    "budget": 2,
    "description": "Un plat simple à base de poulet, oignons, crème et poudre de curry."
  }
}

### Mise à  jour ingredients d'une recette
PUT http://localhost:1337/api/recettes/dd82ffbe-9aa0-4509-902a-59e72f05330b
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "data": {
    "ingredient": [4]
  }
}

### Modifier une recette existante (documentId) (fontionne)
PUT http://localhost:1337/api/recettes/dd82ffbe-9aa0-4509-902a-59e72f05330b
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "budget": 55
  }
}

### Supprimer une recette (documentId) (fonctionne)
DELETE http://localhost:1337/api/recettes/39ab41bd-dcb9-42b5-b16a-8e24c47041e5
Content-Type: application/json
Authorization: Bearer {{token}}